---
- name: Loop Register Test
  hosts: localhost
  gather_facts: no
  tasks: 
    - name: Looping Echo Task
      shell: "echo This is my item {{ item }}"
      loop: 
        - one
        - two
      register: echo_results
    - name: show the output from previous result
      debug: var=echo_results
